topics_keywords = [
    # alt.atheism
    ['secular humanism', 'irreligion', 'critical rationalism', 'empirical skepticism', 'non-theistic ethics',
     'existential nihilism', 'naturalistic worldview', 'disbelief arguments', 'separation of church-state',
     'reasoned inquiry', 'falsifiability principle', 'agnostic realism', 'materialist philosophy',
     'cognitive biases', 'supernatural debunking', 'mythological deconstruction', 'dogmatic rejection',
     'evidentialism', 'enlightenment principles', 'scientific naturalism', 'secular morality',
     'critical biblical scholarship', 'free thought advocacy', 'post-theistic thought', 'logic fallacies'],
    # comp.graphics
    ['photorealistic rendering', 'real-time raytracing', 'GPU compute shaders', 'voxel-based graphics',
     'procedural generation', 'physically-based rendering (PBR)', 'global illumination',
     'subsurface scattering', 'mesh simplification', 'NURBS modeling', 'Bézier surfaces',
     'computational geometry', 'image-based lighting', 'volume rendering', 'point cloud processing',
     'fractal generation', 'inverse kinematics', 'skeletal animation', 'collision detection',
     'GPU accelerated algorithms', 'hdr imaging', 'chroma subsampling', 'texture atlasing',
     'polygon tessellation', 'deferred shading'],
    # comp.os.ms-windows.misc
    ['NTFS permissions', 'registry hive manipulation', 'Group Policy Objects (GPO)', 'PowerShell scripting',
     'Sysinternals tools', 'kernel debugging', 'BSOD analysis', 'DLL injection', 'UAC bypasses',
     'Active Directory trusts', 'COM object registration', 'WMI queries', 'Event Viewer forensics',
     'memory dump analysis', 'driver signing enforcement', 'Windows Management Framework (WMF)',
     'security descriptor definition language (SDDL)', 'Windows Defender ATP', 'Hyper-V checkpoints',
     'disk partitioning schemes', 'bootloader configuration', 'system restore points',
     'Windows Subsystem for Linux (WSL2)', 'credential guard', 'exploit protection (EMET/ASR)'],
    # comp.sys.ibm.pc.hardware
    ['PCIe lane allocation', 'CPU microcode updates', 'ECC memory validation', 'firmware flashing',
     'VRM design', 'power delivery phases', 'thermal throttling', 'liquid metal cooling',
     'custom loop watercooling', 'NVMe protocol', 'RAID controller modes', 'chipset architecture',
     'socket pinout', 'BIOS/UEFI settings', 'POST codes', 'diagnostic LEDs', 'benchmarking suite',
     'power supply efficiency (80 Plus)', 'motherboard VRM', 'integrated graphics performance',
     'discrete GPU VRAM', 'overclocking stability', 'component interoperability',
     'case airflow optimization', 'custom cable management'],
    # comp.sys.mac.hardware
    ['Apple Silicon architecture', 'T2 Security Chip', 'Retina display calibration', 'Thunderbolt 4 bandwidth',
     'Pro Display XDR specifications', 'logic board repair', 'SSD controller wear leveling',
     'MagSafe charging protocol', 'Touch ID sensor integration', 'integrated GPU performance',
     'external GPU (eGPU) compatibility', 'firmware password recovery', 'diagnostics mode',
     'component level repair', 'battery cycle count', 'thermal management profiles',
     'memory upgrade limitations', 'Fusion Drive mechanics', 'display backlight issues',
     'keyboard butterfly mechanism', 'liquid damage assessment', 'flexgate repair',
     'sleep/wake power consumption', 'kernel panics (hardware related)', 'NVRAM/PRAM reset'],
    # comp.windows.x
    ['Xorg configuration files', 'Wayland compositor protocols', 'display server architecture',
     'window manager keybindings', 'GTK theme customization', 'Qt styling sheets',
     'input device remapping (xinput)', 'screen tearing prevention', 'HiDPI scaling',
     'clipboard synchronization (xclip)', 'remote X forwarding (SSH -Y)',
     'display manager greeters', 'compositing effects', 'dotfile management',
     'xrandr monitor setup', 'xprop window properties', 'XRDB resource settings',
     'ibus input methods', 'font rendering antialiasing', 'session management (xdg)',
     'IPC mechanisms (X server)', 'virtual framebuffer (Xvfb)', 'screen capture utilities (scrot)',
     'multi-head display configuration', 'Wayland protocols'],
    # misc.forsale
    ['consignment agreements', 'escrow services', 'market arbitrage', 'liquidation strategy',
     'appraisal valuation', 'authentication verification', 'eBay algorithms', 'Craigslist scams',
     'secondary market analysis', 'seller reputation management', 'shipping logistics optimization',
     'return policy negotiation', 'payment processing fees', 'auction sniping',
     'vintage item restoration', 'collectible grading standards', 'depreciation schedules',
     'resale value prediction', 'bulk purchasing deals', 'private party sales contracts',
     'online marketplace analytics', 'brand authentication', 'condition grading (mint/near mint)',
     'counterfeit detection', 'serialized inventory'],
    # rec.autos
    ['engine ECU tuning', 'suspension geometry', 'aerodynamic drag coefficient', 'tire compound durometer',
     'transmission gear ratios', 'brake fade characteristics', 'fuel injection mapping',
     'turbocharger spool time', 'supercharger boost curve', 'dyno testing', 'engine management systems (EMS)',
     'limited-slip differential (LSD)', 'traction control systems (TCS)', 'ABS calibration',
     'NVH (Noise, Vibration, Harshness)', 'automotive telematics', 'ADAS (Advanced Driver-Assistance Systems)',
     'autonomous driving levels', 'emissions standards (Euro/EPA)', 'vehicle diagnostic codes (OBD-II)',
     'chassis rigidity', 'wheel alignment specs', 'electric vehicle battery degradation',
     'hybrid drivetrain efficiency', 'vehicle-to-grid (V2G) technology'],
    # rec.motorcycles
    ['lean angle sensor', 'traction control modes', 'ABS cornering function', 'throttle-by-wire mapping',
     'suspension preload adjustment', 'tire pressure monitoring systems (TPMS)', 'engine braking control',
     'quick shifter mechanism', 'slip-assist clutch', 'IMU (Inertial Measurement Unit)',
     'rider aids electronics', 'exhaust back pressure', 'frame geometry rake-trail',
     'motorcycle dyno tuning', 'fairing aerodynamic design', 'saddlebag weight distribution',
     'heated grip wiring', 'Bluetooth intercom systems', 'DOT/SNELL helmet standards',
     'motorcycle specific GPS', 'crash bar installation', 'chain lubrication frequency',
     'brake fluid flush intervals', 'throttle body synchronization', 'suspension damping adjustability'],
    # rec.sport.baseball
    ['ERA+ (Earned Run Average Plus)', 'WHIP (Walks plus Hits per Inning Pitched)', 'FIP (Fielding Independent Pitching)',
     'BABIP (Batting Average on Balls In Play)', 'wOBA (Weighted On-Base Average)', 'DRS (Defensive Runs Saved)',
     'UZR (Ultimate Zone Rating)', 'pitch framing', 'exit velocity', 'launch angle',
     'spin rate (fastball/curveball)', 'catcher framing metrics', 'shift defense strategy',
     'bullpen management', 'platoon splits', 'pitcher usage analytics', 'base running efficiency',
     'umpire strike zone analysis', 'sabermetrics', 'WAR (Wins Above Replacement)',
     'pitch sequencing', 'spray charts', 'stolen base percentage', 'quality start definition', 'fWAR'],
    # rec.sport.hockey
    ['Corsi For Percentage (CF%)', 'Fenwick For Percentage (FF%)', 'xG (Expected Goals)',
     'PDO (Shooting Plus Save Percentage)', 'Rel TM (Relative To Teammates)', 'Zone Starts',
     'Goalie GSAA (Goals Saved Above Average)', 'Corsi Against (CA)', 'Fenwick Against (FA)',
     'High-Danger Chances', 'Shot Attempts%', 'Faceoff Win Percentage', 'Power Play Efficiency',
     'Penalty Kill Efficiency', 'Save Percentage (SV%)', 'Shooting Percentage (SH%)',
     'Offensive Zone Time', 'Defensive Zone Time', 'Puck Possession Metrics', 'Breakout Strategy',
     'Forecheck Schemes', 'Backcheck Effort', 'Net Front Presence', 'Shot Blocking Rate', 'Penalty Drawing'],
    # sci.crypt
    ['elliptic curve cryptography (ECC)', 'homomorphic encryption', 'zero-knowledge proofs (ZKP)',
     'post-quantum cryptography', 'side-channel attacks', 'cold boot attack', 'timestamping authority (TSA)',
     'secure multi-party computation (MPC)', 'blockchain consensus algorithms', 'cryptographic hash functions',
     'digital signature algorithms (DSA)', 'key derivation functions (KDF)', 'perfect forward secrecy',
     'quantum key distribution (QKD)', 'hardware security modules (HSM)', 'trusted execution environments (TEE)',
     'format-preserving encryption (FPE)', 'merkle trees', 'secure element', 'pseudorandom number generators (PRNG)',
     'salting passwords', 'key stretching', 'trapdoor functions', 'symmetric key derivation', 'threshold cryptography'],
    # sci.electronics
    ['Op-Amp gain-bandwidth product', 'Nyquist-Shannon sampling theorem', 'Kirchhoff current law (KCL)',
     'Kirchhoff voltage law (KVL)', 'Thevenin equivalent circuit', 'Norton equivalent circuit',
     'Bode plots', 'Smith charts', 'SPICE simulation', 'FPGA programming (Verilog/VHDL)',
     'SMD soldering (Surface Mount Device)', 'logic gate propagation delay', 'ADC/DAC resolution',
     'PWM control (Pulse Width Modulation)', 'resonant frequency', 'impedance matching',
     'transistor biasing techniques', 'datasheet interpretation', 'ESD protection (Electrostatic Discharge)',
     'EMC/EMI compliance', 'signal integrity', 'power integrity', 'PCB trace impedance',
     'microcontroller interrupt handling', 'PID control loops'],
    # sci.med
    ['CRISPR gene editing', 'mRNA vaccine technology', 'CAR T-cell therapy', 'pharmacogenomics',
     'epigenetic modifications', 'microbiome analysis', 'precision oncology', 'liquid biopsy diagnostics',
     'neuroimaging fMRI', 'immunotherapy mechanisms', 'CRISPR-Cas9 ethics', 'personalized medicine',
     'bioinformatics algorithms', 'drug repurposing', 'radiomics', 'telehealth platforms',
     'medical device biocompatibility', 'clinical trial phases', 'drug-drug interactions',
     'genomic sequencing interpretation', 'pathogen virulence factors', 'autoimmune disease mechanisms',
     'neurodegenerative pathways', 'pharmacokinetics/pharmacodynamics', 'targeted drug delivery'],
    # sci.space
    ['orbital mechanics equations', 'propellant specific impulse', 'gravitational slingshot maneuver',
     'L-points (Lagrangian points)', 're-entry heat shield ablation', 'spacecraft attitude control',
     'ion propulsion systems', 'space debris mitigation', 'astro-spectroscopy', 'exoplanet transit detection',
     'cosmic microwave background (CMB)', 'gravitational lensing phenomena', 'black hole event horizons',
     'dark matter detection experiments', 'dark energy equation of state', 'interstellar medium composition',
     'stellar nucleosynthesis', 'gamma-ray burst mechanisms', 'planetary atmospheric escape',
     'terraforming feasibility', 'Dyson sphere concepts', 'Alcubierre drive theory',
     'radio astronomy interferometry', 'SETI signal analysis', 'solar wind interaction'],
    # soc.religion.christian
    ['biblical hermeneutics', 'christological debates', 'trinitarian theology', 'soteriology (doctrine of salvation)',
     'ecclesiology (doctrine of the church)', 'eschatology (study of end times)',
     'patristic writings', 'reformation theology', 'sacramental theology', 'Christian apologetics',
     'covenant theology', 'dispensationalism', 'predestination doctrine', 'free will theology',
     'synoptic problem', 'textual criticism (biblical)', 'church history periods', 'Christian ethics (metaethics)',
     'spiritual formation practices', 'missional ecclesiology', 'liturgical practices', 'canon formation',
     'Anabaptist theology', 'Reformed epistemology', 'Christian mysticism'],
    # talk.politics.guns
    ['NFA (National Firearms Act) items', 'ATF regulations', 'Universal Background Checks',
     'Red Flag Laws (Extreme Risk Protection Orders)', 'Constitutional carry legislation',
     'assault weapon bans', 'magazine capacity restrictions', 'federal firearms licensees (FFL)',
     'gun show loophole debates', 'concealed carry reciprocity', 'ghost gun manufacturing',
     'ballistic fingerprinting', 'microstamping technology', 'straw purchase penalties',
     'school zone gun bans', 'bump stock regulations', 'ITAR (International Traffic in Arms Regulations)',
     'gun violence epidemiology', 'pro-gun lobbying', 'anti-gun advocacy',
     'firearm preemption laws', 'Militia Clause interpretation', 'Heller v. DC (2008)',
     'McDonald v. Chicago (2010)', 'Safe Storage laws'],
    # talk.politics.mideast
    ['Two-State Solution viability', 'Oslo Accords implementation', 'settlement expansion impact',
     'Jerusalem status negotiations', 'Gaza blockade humanitarian crisis', 'West Bank occupation legalities',
     'Iran nuclear deal (JCPOA)', 'Syrian civil war proxies', 'Lebanese sectarian power-sharing',
     'Kurdish self-determination', 'GCC (Gulf Cooperation Council) politics', 'OPEC oil production quotas',
     'Arab Spring ripple effects', 'geopolitical energy security', 'proxy conflict dynamics',
     'Abraham Accords implications', 'UNRWA mandate', 'human rights violations (specific cases)',
     'water resource allocation', 'historical land claims', 'refugee resettlement policies',
     'extremist group financing', 'de-escalation strategies', 'international mediation efforts',
     'sectarian conflict dynamics'],
    # talk.politics.misc
    ['gerrymandering strategies', 'voter ID laws impact', 'campaign finance regulations',
     'dark money in politics', 'judicial review precedents', 'legislative filibuster reform',
     'executive order scope', 'administrative state oversight', 'populist movement analysis',
     'neoliberal economic policy', 'critical race theory debates', 'intersectional feminism',
     'climate change policy implementation', 'universal basic income (UBI) models',
     'carbon pricing mechanisms', 'supply-side economics', 'monetary policy inflation targets',
     'foreign aid effectiveness', 'cyber warfare doctrines', 'disinformation campaigns',
     'social media political influence', 'civic engagement theories', 'global governance frameworks',
     'humanitarian intervention legality', 'international criminal court jurisdiction'],
    # talk.religion.misc
    ['religious pluralism theories', 'interfaith dialogue methodologies', 'secular humanism tenets',
     'new religious movement typology', 'cultic studies models', 'mystical experience phenomenology',
     'religious syncretism', 'spiritual but not religious (SBNR) demographics',
     'cognitive science of religion', 'neurotheology', 'religious trauma syndrome',
     'exclusivism vs. inclusivism', 'religious freedom legislation', 'apostasy narratives',
     'conversion experience psychology', 'religious fundamentalism dynamics', 'atheist identity formation',
     'theodicy problem', 'problem of evil', 'religious ethics applications',
     'mythopoetic interpretations', 'contemplative practice outcomes', 'secularization theory',
     'religious disaffiliation trends', 'spiritual bypassing']
]

import json

with open("topics_keywords.json", "w", encoding="utf-8") as f:
    json.dump(topics_keywords, f, ensure_ascii=False, indent=2)

print("Keywords written to topics_keywords.json")